export const LATITUDE_LONGITUDE_FETCH = 'LATITUDE_LONGITUDE/FETCH'
export const LATITUDE_LONGITUDE_FETCH_SUCCESS = 'LATITUDE_LONGITUDE/FETCH_SUCCESS'
export const LATITUDE_LONGITUDE_FETCH_FAILURE = 'LATITUDE_LONGITUDE/FETCH_FAILURE'

export const WEATHER_FETCH = 'WEATHER/FETCH'

export const CURRENT_WEATHER_FETCH_SUCCESS = 'CURRENT_WEATHER/FETCH_SUCCESS'
export const CURRENT_WEATHER_FETCH_FAILURE = 'CURRENT_WEATHER/FETCH_FAILURE'

export const FOUR_DAY_WEATHER_FETCH_SUCCESS = 'FOUR_DAY_WEATHER/FETCH_SUCCESS'
export const FOUR_DAY_WEATHER_FETCH_FAILURE = 'FOUR_DAY_WEATHER/FETCH_FAILURE'