export const LATITUDE_LONGITUDE_FETCH = 'LATITUDE_LONGITUDE/FETCH'
export const LATITUDE_LONGITUDE_FETCH_SUCCESS = 'LATITUDE_LONGITUDE/FETCH_SUCCESS'
export const LATITUDE_LONGITUDE_FETCH_FAILURE = 'LATITUDE_LONGITUDE/FETCH_FAILURE'